FROM ubuntu:18.04

ENV HELM_VERSION=v3.3.1

# Install git & requests
RUN apt update && \
    apt install git -y && \
    apt install wget -y && \
    apt install curl -y
    
# Install Helm
RUN wget https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz && \
    tar -zxvf helm-$HELM_VERSION-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm

# Clean package
RUN apt clean && \
    apt autoclean && \
    apt autoremove --purge
