FROM ubuntu:18.04

# Install git & requests
RUN apt update && \
    apt install git -y && \
    apt install wget -y
    
# Install Helm
RUN wget https://get.helm.sh/helm-v3.3.1-linux-amd64.tar.gz && \
    tar -zxvf helm-v3.0.0-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/local/bin/helm

# Clean package
RUN apt clean && \
    apt autoclean && \
    apt autoremove --purge
